### ISSUE TITLE
Decoding of Base64 body

### ISSUE THREAD

**Issue by felixhammerl** [emailjs/emailjs-mime-parser#18]
The decoding of Base64 body in the body of the MIME node is currently a bit hit-or miss.

* Base64 is decoded into a typed array: https://github.com/emailjs/emailjs-mime-codec/blob/master/src/mimecodec.js#L84
* MIME node charset is ignored
* Typed array is decoded by trying out UTF-8, Latin-9, and then falling back to binary: https://github.com/emailjs/emailjs-mime-codec/blob/master/src/charset.js#L20

Proposed fix: 
* For MIME nodes with charset provided: use the charset provided by the Content-Type used during the encoding
* For non-`text/*` MIME nodes without charset: use binary
* For `text/*` without charset: fall back to the UTF-8 -> Latin-9 -> binary heuristic

Does that make sense?

**Comment by SPodjasek** [comment]
I've just run into issues that this fix should resolve.

I receive message with following part in it:

```
Content-Type: application/pdf; name=9000011681201803130140.7z
Content-Transfer-Encoding: base64
Content-Disposition: attachment; filename=9000011681201803130140.7z
```

Besides that it specifies wrong `Content-Type` for file attached, it doesn't specify charset. So as for now this is parsed as UTF-8 string and in result I get broken file with 459 bytes instead of 490 in it.

As a temporary solution I've modified `_processBodyLine` by adding
```javascript
if (!this.charset) { this.charset = 'binary' }
```

But your solution seems to handle this in more complex manner.

**Comment by felixhammerl** [comment]
I've just not gotten around to spending more time on this recently...

I'm not sure what should be the default charset... I've got it at utf-8 for now, since my assumption was that most of the emails will probably be sent as text ... i'm not so sure about that anymore. I guess i should probably change that to binary, as you suggested.

**Comment by SPodjasek** [comment]
Looking at some mails in my mailbox I believe that it's very common to see binary attachments encoded in base64 without charset specified in `Content-Type`, only `text/*` parts seem to specify charset. So assuming binary as default would probably "break less things", then assuming UTF-8 to everything.

**Comment by felixhammerl** [comment]
You are absolutely right. This is the next thing on my list after refatoring the dreaded smtp client :)

**Comment by kams-mash** [comment]
@felixhammerl : I ran into the same issues :) - not seeing charset defined for attachments in rfc data from popular clients like gmail/outlook, and as utf-8 is used as default instead of binary, the attachments are not decoded!

I created a pull request #32, would love to hear any feedback or if it could be merged if it looks good. I tested with different combinations and seems to hold good.

**Comment by felixhammerl** [comment]
Fixed with https://github.com/emailjs/emailjs-mime-parser/pull/32

**Comment by felixhammerl** [comment]
published as `v2.0.5`

**Comment by felixhammerl** [comment]
Thanks everyone involved and especially @kams-mash for providing the fix!

**Comment by nifgraup** [comment]
Here https://github.com/tanx/mailreader/blob/b14998ca26cb612bbdb495375a412b4247997833/test/test.js#L99 is a test fixture that fails decoding because it doesn't have `Content-Disposition: attachment` or `Content-Disposition: inline`. Maybe it would be best to not require that? That would be more in line with this discussion.
